### ISSUE TITLE
Error message when adding account that supports Automx

### ISSUE THREAD

**Issue by haeihaiehaei** [sys4/automx#42]
Hi, we are trying out Modoboa which installs AutoMX automatically but when I try to add an account I get the following error:

```
2017-10-09 10:40:01,436 WARNING: No SQL result from server!
2017-10-09 10:40:01,436 WARNING: Request 2 [IP]
autodiscover.domain.com[pid: 1227|app: 0|req: 3/5] IP() {62 vars in 1038 bytes} [Mon Oct  9 10:40:01 2017] POST /autodiscover/autodiscover.xml => generated 0 bytes in 11 msecs (HTTP/1.1 500) 2 headers in 81 bytes (2 switches on core 0)
Traceback (most recent call last):
  File "./automx_wsgi.py", line 126, in application
    tree = etree.parse(fd)
  File "src/lxml/lxml.etree.pyx", line 3442, in lxml.etree.parse (src/lxml/lxml.etree.c:81716)
  File "src/lxml/parser.pxi", line 1828, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118859)
  File "src/lxml/parser.pxi", line 1843, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:119069)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
autodiscover.domain.com [pid: 1227|app: 0|req: 4/6] 91.189.40.200 () {46 vars in 748 bytes} [Mon Oct  9 10:40:01 2017] POST /autodiscover/autodiscover.xml => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```
I've talked to the developer of Modoboa and this error seems to be pointing towards Automx itself.

**Comment by gianks** [comment]
Hi, i think this is related to this other issue https://github.com/modoboa/modoboa-installer/issues/174 and it is still a problem since i'm experiencing error 500 on autoconfig requests through a modoboa installation.
Can someone help on this?

Thanks
